apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cost-estimation
  name: cost-estimation
  namespace: devstination
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: cost-estimation
        env:
        - name: ENVIRONMENT
          value: production
        image: registry.digitalocean.com/devstination/cost-estimation-production:${SHORT_SHA}
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi