apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namePrefix: staging-

commonLabels:
    app: cost-estimation

bases:
  - ../../base

#resources:
#  - NewFileNotInBase.yaml

patchesStrategicMerge:
  - deployment.yaml

namespace: devstination