name: Build-Push-cost-estimation-Development-PR

on:
  pull_request:
    branches:
      - development
jobs:

  build:
    environment: staging
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate Docker metadata for cost-estimation
      id: meta-cost-estimation
      uses: docker/metadata-action@v3
      with:
        images: |
          registry.digitalocean.com/devstination/cost-estimation-staging-pr
        tags: |
          type=ref,event=tag
          type=sha,prefix=,suffix=,format=short

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DigitalOcean Registry
      uses: docker/login-action@v2
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DIGITAL_OCEAN_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.DIGITAL_OCEAN_CONTAINER_REGISTRY_PASSWORD }}

    - name: update cost-estimation .env with secrets values - staging
      env:
        NEXT_PUBLIC_ENV: ${{ vars.NEXT_PUBLIC_ENV }}
        LOG_LEVEL: ${{ vars.LOG_LEVEL }}
        LOG_FORMAT: ${{ vars.LOG_FORMAT }}
        REDACT_FIELDS: ${{ vars.REDACT_FIELDS }}
        NEXT_PUBLIC_API_BASE_URL: ${{ vars.NEXT_PUBLIC_API_BASE_URL }}
      run: |
        envsubst < .env.ci > .env.ci.tmp
        rm -rf .env || true
        mv .env.ci.tmp .env
        
    - name: Build and push cost-estimation
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta-cost-estimation.outputs.tags }}
        labels: ${{ steps.meta-cost-estimation.outputs.labels }}
