name: Build-Push-deploy-cost-estimation-Staging

on:
  push:
    branches:
      - development

jobs:

  build:
    environment: staging
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate Docker metadata for cost-estimation
      id: meta-cost-estimation-staging
      uses: docker/metadata-action@v3
      with:
        images: |
          registry.digitalocean.com/devstination/cost-estimation-staging
        tags: |
          type=ref,event=tag
          type=sha,prefix=,suffix=,format=short
        flavor: |
          latest=true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DigitalOcean Registry
      uses: docker/login-action@v2
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DIGITAL_OCEAN_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.DIGITAL_OCEAN_CONTAINER_REGISTRY_PASSWORD }}

#    - name: update cost-estimation .env with secrets values - staging
#      env:
#        NEXT_PUBLIC_ENV: ${{ vars.NEXT_PUBLIC_ENV }}
#      run: |
#        envsubst < .env.ci > .env.ci.tmp
#        rm -rf .env || true
#        mv .env.ci.tmp .env
        
    - name: Build and push cost-estimation
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta-cost-estimation-staging.outputs.tags }}
        labels: ${{ steps.meta-cost-estimation-staging.outputs.labels }}

  deploy_cost-estimation_k8s-staging:
    environment: staging
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/development') }}
    steps:
      - uses: actions/checkout@v3

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Kustomize and validate k8s-manifests
        uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kubeconform
            kustomize
          kubeconform: '0.5.0'
          kustomize: '4.5.7'
      - run: |
          kustomize build k8s-manifests/environments/staging | kubeconform -verbose
          kustomize build k8s-manifests/environments/staging > ./staging-cost-estimation.yaml

      - name: update cost-estimation with secrets values - DockerImage SHORT_SHA
        run: |
          envsubst < staging-cost-estimation.yaml > staging-cost-estimation.yaml.tmp
          mv staging-cost-estimation.yaml.tmp staging-cost-estimation.yaml

      - name: K8s-set-context to DO staging cluster
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_DO_STAGING }}

      - name: Deploy to the DO staging cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: devstination
          manifests: |
            staging-cost-estimation.yaml
